AllCops:
  DisplayCopNames: true

LineLength:
  Max: 128

MethodLength:
  Max: 25

Encoding:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
