AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
