#!/usr/bin/env ruby
# frozen_string_literal: true

require "shellwords"
require "socket"

if ARGV[0].nil? || ARGV[0].empty? || ARGV[0] == "-h" || ARGV[0] == "--help"
  puts "\nUsage: debug-socket <socket-path> [<command>=backtrace]"
  exit 1
end

socket_path = ARGV[0]
command = ARGV[1] || "backtrace"

warn "\nSending `#{command}` to the following socket: #{socket_path}"\
  "----------------------------------------------------------\n\n"

UNIXSocket.open(socket_path) do |socket|
  socket.write(command)
  socket.close_write
  puts socket.read
end
